name: streams_channel_example
description: Demonstrates how to use the streams_channel plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  streams_channel:
    path: ../
